# Generated by Django 5.2.10 on 2026-01-20 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre de la categoría (ej: Instrumentos, Kits)",
                        max_length=100,
                        unique=True,
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="Identificador URL-friendly (se genera automáticamente)",
                        max_length=100,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Descripción opcional de la categoría",
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoría",
                "verbose_name_plural": "Categorías",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre descriptivo del producto",
                        max_length=200,
                        verbose_name="Nombre del producto",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Descripción detallada del producto",
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Precio en dólares con 2 decimales",
                        max_digits=10,
                        verbose_name="Precio ($)",
                    ),
                ),
                (
                    "stock_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Número de unidades disponibles",
                        verbose_name="Cantidad en stock",
                    ),
                ),
                (
                    "in_stock",
                    models.BooleanField(
                        default=False,
                        editable=False,
                        help_text="Indica si hay unidades disponibles (se calcula automáticamente)",
                        verbose_name="En stock",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Foto del producto (formatos: JPG, PNG)",
                        null=True,
                        upload_to="products/",
                        verbose_name="Imagen",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Categoría a la que pertenece el producto",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="products.category",
                        verbose_name="Categoría",
                    ),
                ),
            ],
            options={
                "verbose_name": "Producto",
                "verbose_name_plural": "Productos",
                "ordering": ["-created_at"],
            },
        ),
    ]
