# Generated by Django 5.2.10 on 2026-01-20 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="discount_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Precio con descuento (dejar vacío si no hay oferta)",
                max_digits=10,
                null=True,
                verbose_name="Precio de oferta ($)",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Precio normal en dólares",
                max_digits=10,
                verbose_name="Precio regular ($)",
            ),
        ),
    ]
