# Generated by Django 5.2.10 on 2026-01-20 20:42

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_product_image_productimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Foto principal del producto (formatos: JPG, PNG)",
                null=True,
                upload_to=products.models.path_and_rename,
                verbose_name="Imagen principal",
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                help_text="Imagen adicional del producto",
                upload_to=products.models.gallery_path_and_rename,
                verbose_name="Imagen",
            ),
        ),
    ]
