# Generated by Django 5.2.10 on 2026-01-27 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_brand_product_brand"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="target_audience",
            field=models.CharField(
                choices=[
                    ("STUDENT", "Estudiantes"),
                    ("PROFESSIONAL", "Profesionales"),
                    ("GENERAL", "Todos / Ambos"),
                ],
                default="GENERAL",
                help_text="¿A quién va dirigido este producto? (Estudiantes, Profesionales o Ambos)",
                max_length=15,
                verbose_name="Audiencia objetivo",
            ),
        ),
    ]
