# Generated by Django 5.2.10 on 2026-01-27 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_add_target_audience"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="target_audience",
            field=models.CharField(
                choices=[
                    ("STUDENT", "Estudiantes"),
                    ("PROFESSIONAL", "Profesionales"),
                    ("GENERAL", "Todos / Ambos"),
                ],
                default="GENERAL",
                help_text="¿A quién va dirigida esta marca? (Estudiantes, Profesionales o Ambos)",
                max_length=15,
                verbose_name="Audiencia objetivo",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="target_audience",
            field=models.CharField(
                choices=[
                    ("STUDENT", "Estudiantes"),
                    ("PROFESSIONAL", "Profesionales"),
                    ("GENERAL", "Todos / Ambos"),
                ],
                default="GENERAL",
                help_text="¿A quién va dirigida esta categoría? (Estudiantes, Profesionales o Ambos)",
                max_length=15,
                verbose_name="Audiencia objetivo",
            ),
        ),
    ]
