# Generated by Django 5.2.10 on 2026-01-30 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_add_target_audience_to_category_brand"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="cost_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Cuánto costó comprar este producto (para calcular ganancia)",
                max_digits=10,
                null=True,
                verbose_name="Precio de costo ($)",
            ),
        ),
    ]
