# Generated by Django 5.2.10 on 2026-01-30 13:01

import django.db.models.deletion
import finance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0008_product_cost_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "concept",
                    models.CharField(
                        help_text="Descripción breve del gasto",
                        max_length=200,
                        verbose_name="Concepto",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Valor del gasto en dólares",
                        max_digits=10,
                        verbose_name="Monto ($)",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("MARKETING", "Marketing"),
                            ("LOGISTICS", "Logística"),
                            ("OPERATIONS", "Operativo"),
                            ("INVENTORY", "Inventario"),
                            ("UTILITIES", "Servicios"),
                            ("OTHER", "Otros"),
                        ],
                        default="OTHER",
                        help_text="Tipo de gasto para análisis",
                        max_length=20,
                        verbose_name="Categoría",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        help_text="Cuándo se realizó el gasto",
                        verbose_name="Fecha del gasto",
                    ),
                ),
                (
                    "receipt",
                    models.FileField(
                        blank=True,
                        help_text="Factura o recibo (opcional)",
                        null=True,
                        upload_to=finance.models.receipt_path,
                        verbose_name="Comprobante",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Observaciones adicionales",
                        verbose_name="Notas",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de registro"
                    ),
                ),
            ],
            options={
                "verbose_name": "Gasto",
                "verbose_name_plural": "Gastos",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        help_text="Número de unidades vendidas", verbose_name="Cantidad"
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Precio por unidad en el momento de la venta",
                        max_digits=10,
                        verbose_name="Precio unitario de venta ($)",
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Costo del producto (se autocompleta si está disponible)",
                        max_digits=10,
                        null=True,
                        verbose_name="Costo unitario ($)",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        help_text="Calculado automáticamente",
                        max_digits=12,
                        verbose_name="Total de la venta ($)",
                    ),
                ),
                (
                    "sale_date",
                    models.DateTimeField(
                        help_text="Cuándo se realizó la venta",
                        verbose_name="Fecha de venta",
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(
                        blank=True,
                        help_text="Nombre del cliente (opcional)",
                        max_length=200,
                        verbose_name="Cliente",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Observaciones de la venta",
                        verbose_name="Notas",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de registro"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Producto vendido",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales",
                        to="products.product",
                        verbose_name="Producto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Venta",
                "verbose_name_plural": "Ventas",
                "ordering": ["-sale_date", "-created_at"],
            },
        ),
    ]
